INSERT OR REPLACE INTO BaseGameText(Tag,										Text)
VALUES	('LOC_PEDIA_LEADERS_PAGE_LEADER_CN_CAO_CAO_TITLE',						'Cao Cao'),
		('LOC_PEDIA_LEADERS_PAGE_LEADER_CN_CAO_CAO_SUBTITLE',					'The Wu emperor of Wei'),
		('LOC_PEDIA_LEADERS_PAGE_LEADER_CN_CAO_CAO_CHAPTER_HISTORY_PARA_1',		'The general trend of the country is to divide when unification has lasted for a long time, and to unite when division has lasted for a long time. When the powerful Han Dynasty finally went in its twilight, rebel warlords and insurgent armies fought fiercely everywhere. It was the founder of the Wei Dynasty, Cao Cao, who finally defeated many opponents and unified the northern China.'),
		('LOC_PEDIA_LEADERS_PAGE_LEADER_CN_CAO_CAO_CHAPTER_HISTORY_PARA_2',		'Cao Cao was a clever young man who, at the age of twenty, entered the civil service through the filial appointment and later became involved in the suppression of the Yellow Turban Army. When the warlord Dong Zhuo took control of the court at the end of the Han dynasty, Cao Cao spread his wealth and raised an army to join Yuan Shao and others in their crusade against Dong Zhuo. 192 years later, Cao Cao occupied Yanzhou and collected over 300,000 Yellow Turban troops who had surrendered, from which he chose the best to form the Qingzhou army. In 196, Cao Cao escorted the Han Emperor to Xudu, while he himself became the Secretary General and exercised the authority of the Cheqi General, taking control of the court. In 200, Cao Cao defeated main forces of Yuan Shao in the decisive Battle of Guandu. In 208, Cao Cao became prime minister and then led an expedition south to force Liu Cong of Jingzhou to surrender, but was defeated by the allied forces of Sun Quan and Liu Bei at the Battle of Chibi. In 211, Cao Cao defeated the allied forces of Guanzhong at the Battle of Weinan. In 213, Cao Cao was crowned Duke of Wei. In 215, Cao Cao personally led an expedition against Zhang Lu and recovered Hanzhong. In 216, Cao Cao was crowned King of Wei.'),
		('LOC_PEDIA_LEADERS_PAGE_LEADER_CN_CAO_CAO_CHAPTER_HISTORY_PARA_3',		'Cao Cao was a great military man, statesman and man of letters, who helped to restore and develop the economy of the Han Dynasty. He knew the art of war and was good at poetry, expressing his political ambitions and reflecting the suffering of the people at the end of the Han Dynasty. Many of his literary works are included in Chinese textbooks and are studied by all chinese students. Today there is a collection of his works. His "A Brief Explanation of Sun Tzu" has also been published. Cao Cao was also very good at calligraphy, and his calligraphy was described in the famous book "Shu Duan" as "a wonderful work".'),
		('LOC_PEDIA_LEADERS_PAGE_LEADER_CN_CAO_CAO_CHAPTER_HISTORY_PARA_4',		'In 220, Cao Cao died of illness in Luoyang and was buried at the age of sixty-six in the Gao Tomb. Cao Cao was honoured with the temple name of Taizu and the posthumous name of Emperor Wu after his son Cao Pi became the first emperor of Wei Dynasty.'),
		('LOC_PEDIA_LEADERS_PAGE_LEADER_CN_CAO_CAO_CHAPTER_DETAILED_BODY',		'Cao Cao was powerful in seeking for victory of culture, conquest and technology.'),
		('LOC_PEDIA_LEADERS_PAGE_LEADER_CN_CAO_CAO_CHAPTER_CAPSULE_BODY',		'Cao Cao is a leader who develops in many ways. His Leader Ability allows him to easily gain [ICON_Culture] Culture, and by creating a large central city he can quickly develop surrounding cities using [ICON_TradeRoute] Trade Routes. His bonuses to building  allow him to quickly bolster his output of his cities. Whether he is using [ICON_Gold] Gold to support a large army in his quest for conquest, or using [ICON_Gold] Gold to speed up the building of cities and pursue cultural or technological victories, Cao Cao is a good choice.'),
		('LOC_PEDIA_UNITS_PAGE_UNIT_TIGER_CAVALRY_TITLE',						'Hubao Cavalry'),
		('LOC_PEDIA_UNITS_PAGE_UNIT_TIGER_CAVALRY_CHAPTER_HISTORY_PARA_1',		'To Cao Cao, the Hubao Cavalry was his most relied upon elite army. Hu means tiger and bao means leopard, in chinese we use these animals to describe a person who has high combat strength. A man who could be a general in an ordinary army was a mere soldier in the Hubao Cavalry, so you can imagine that its combat power was the highest among the Three Kingdoms.');
	