INSERT OR REPLACE INTO BaseGameText(Tag,										Text)
VALUES	('LOC_PEDIA_LEADERS_PAGE_LEADER_CN_CAO_CAO_TITLE',						'Xiao Yan'),
		('LOC_PEDIA_LEADERS_PAGE_LEADER_CN_CAO_CAO_SUBTITLE',					'Emperor Wu of Liang dynasty'),
		('LOC_PEDIA_LEADERS_PAGE_LEADER_CN_CAO_CAO_CHAPTER_HISTORY_PARA_1',		'Emperor Wu of Liang, formerly known as Xiao Yan, is the founder of Southern Liang during the Northern and Southern Dynasties of China. He ascended the throne in 502 and established the Liang Dynasty, as a unique leader who was a literary scholar, historian, Buddhist, as well as a statesman and militarist. His reign is considered to be the golden age of culture and Buddhism in the Southern Dynasties.'),
		('LOC_PEDIA_LEADERS_PAGE_LEADER_CN_CAO_CAO_CHAPTER_HISTORY_PARA_2',		'The deep faith of Xiao Yan in Buddhism had a significant impact on his rule. Known as the "Monk Emperor" who produced a large body of work as a scholar in the fields of scripture and Buddhism, he established numerous Buddhist temples throughout the country and contributed to the development of Buddhist art and architecture. He is also a prolific poet who made important contributions to Chinese literature. Furthermore, in terms of historiography, he was dissatisfied with the writing of dynastic histories, such as the Book of Han, and thus presided over the compilation of the 600-volume Tongshi (General History).'),
		('LOC_PEDIA_LEADERS_PAGE_LEADER_CN_CAO_CAO_CHAPTER_HISTORY_PARA_3',		'Despite his cultural and religious accomplishments, Emperor Wu of Liang performed only so-so politically. In the early part of his reign, his hard work brought prosperity and stability to the south. However, in the latter part of his reign, there were frequent political upheavals and military conflicts in the country, mainly due to the neglect of political affairs as a result of his excessive devotion to Buddhism.'),
		('LOC_PEDIA_LEADERS_PAGE_LEADER_CN_CAO_CAO_CHAPTER_HISTORY_PARA_4',		'The later years of Xiao Yan were plagued by political turmoil and war. 549 saw the outbreak of the Hou Jing Rebellion and the capture of Xiao Yan. He died of hunger, thirst and anger at the age of 86, ending his nearly half-century-long reign. He was buried in Xiu Mausoleum (present-day Lingkou, Danyang City, Jiangsu Province). His posthumous name was Emperor Wu and his temple name was Gaozu.'),
		('LOC_PEDIA_LEADERS_PAGE_LEADER_CN_CAO_CAO_CHAPTER_HISTORY_PARA_5',		'The reign of Emperor Wu of Liang was the golden age of culture and Buddhism in Southern China. Although his rule was not perfect, his cultural and religious contributions were remembered for generations to come.'),
		('LOC_PEDIA_LEADERS_PAGE_LEADER_CN_CAO_CAO_CHAPTER_DETAILED_BODY',		''),
		('LOC_PEDIA_LEADERS_PAGE_LEADER_CN_CAO_CAO_CHAPTER_CAPSULE_BODY',		'');	