/*
	Ai Info
	Authors: Burkart
*/

-----------------------------------------------
-- AiListTypes
-----------------------------------------------

INSERT INTO AiListTypes
		(ListType					        )
VALUES 	('LEADER_CN_XIAOYAN_VICS'			),
		('LEADER_CN_XIAOYAN_TECHS'			),
		('LEADER_CN_XIAOYAN_CIVICS'		    ),
		('LEADER_CN_XIAOYAN_DISTRICTS'		),
		('LEADER_CN_XIAOYAN_BUILDINGS'		),
		('LEADER_CN_XIAOYAN_PROJECTS'		),
		('LEADER_CN_XIAOYAN_DIPLOMACY'		),
		('LEADER_CN_XIAOYAN_UNITS'			),
		('LEADER_CN_XIAOYAN_TACTICS'		),
		('LEADER_CN_XIAOYAN_EXPANSION'		),
		('LEADER_CN_XIAOYAN_PSUEDOS'		),
		-- XP1
		('LEADER_CN_XIAOYAN_ALLIANCES'		),
		('LEADER_CN_XIAOYAN_COMMEMORATIONS'),
		-- XP2
		('LEADER_CN_XIAOYAN_DISCUSSIONS'	);

-----------------------------------------------
-- AiLists
-----------------------------------------------

INSERT INTO AiLists
		(ListType,									AgendaType,						System				) -- AgendaType links to a TraitType, not an AgendaType... :/
VALUES  ('LEADER_CN_XIAOYAN_VICS',					'TRAIT_LEADER_CN_XIAOYAN_UA',	'Strategies'		),
		('LEADER_CN_XIAOYAN_TECHS',					'TRAIT_LEADER_CN_XIAOYAN_UA',	'Technologies'		),
		('LEADER_CN_XIAOYAN_CIVICS',				'TRAIT_LEADER_CN_XIAOYAN_UA',	'Civics'			),
		('LEADER_CN_XIAOYAN_DISTRICTS',				'TRAIT_LEADER_CN_XIAOYAN_UA',	'Districts'			),
		('LEADER_CN_XIAOYAN_BUILDINGS',				'TRAIT_LEADER_CN_XIAOYAN_UA',	'Buildings'			),
		('LEADER_CN_XIAOYAN_PROJECTS',				'TRAIT_LEADER_CN_XIAOYAN_UA',	'Projects'			),
		('LEADER_CN_XIAOYAN_UNITS',					'TRAIT_LEADER_CN_XIAOYAN_UA',	'Units'				),
		('LEADER_CN_XIAOYAN_TACTICS',				'TRAIT_LEADER_CN_XIAOYAN_UA',	'Tactics'			),
		('LEADER_CN_XIAOYAN_DIPLOMACY',				'TRAIT_LEADER_CN_XIAOYAN_UA',	'DiplomaticActions'	),
		('LEADER_CN_XIAOYAN_EXPANSION',				'TRAIT_LEADER_CN_XIAOYAN_UA',	'PlotEvaluations'	),
		('LEADER_CN_XIAOYAN_PSUEDOS',				'TRAIT_LEADER_CN_XIAOYAN_UA',	'PsuedoYields'		),
		-- XP1
		('LEADER_CN_XIAOYAN_ALLIANCES',				'TRAIT_LEADER_CN_XIAOYAN_UA',	'Alliances'			),
		('LEADER_CN_XIAOYAN_COMMEMORATIONS',		'TRAIT_LEADER_CN_XIAOYAN_UA',	'Commemorations'	),
		-- XP2
		('LEADER_CN_XIAOYAN_DISCUSSIONS',			'TRAIT_LEADER_CN_XIAOYAN_UA',	'Discussions'		);

-----------------------------------------------
-- AiFavoredItems
-----------------------------------------------

INSERT INTO AiFavoredItems
		(ListType,									Item,									Favored	)
VALUES  -- VICS
		('LEADER_CN_XIAOYAN_VICS',					'VICTORY_STRATEGY_CULTURAL_VICTORY',	1,		),
		('LEADER_CN_XIAOYAN_VICS',					'VICTORY_STRATEGY_RELIGIOUS_VICTORY',	1,		),
		-- TECHS
		('LEADER_CN_XIAOYAN_TECHS',					'TECH_CURRENCY',						1		), 
		('LEADER_CN_XIAOYAN_TECHS',					'TECH_ANIMAL_HUSBANDRY',				1		),
		('LEADER_CN_XIAOYAN_TECHS',					'TECH_BRONZE_WORKING',					1		),
		('LEADER_CN_XIAOYAN_TECHS',					'TECH_MASONRY',							1		),
		('LEADER_CN_XIAOYAN_TECHS',					'TECH_HORSEBACK_RIDING',				1		),
		('LEADER_CN_XIAOYAN_TECHS',					'TECH_WRITING',							1		),
		('LEADER_CN_XIAOYAN_TECHS',					'TECH_RADIO',							1		),
		('LEADER_CN_XIAOYAN_TECHS',					'TECH_ROCKETRY',						1		),
		-- CIVICS
		('LEADER_CN_XIAOYAN_CIVICS',				'CIVIC_FOREIGN_TRADE',					1		),
		('LEADER_CN_XIAOYAN_CIVICS',				'CIVIC_MILITARY_TRADITION',				1		),
		('LEADER_CN_XIAOYAN_CIVICS',				'CIVIC_STATE_WORKFORCE',				1		), 
		('LEADER_CN_XIAOYAN_CIVICS',				'CIVIC_DRAMA_POETRY',					1		),
		('LEADER_CN_XIAOYAN_CIVICS',				'CIVIC_EXPLORATION',					1		),
		('LEADER_CN_XIAOYAN_CIVICS',				'CIVIC_FEUDALISM',						1		),
		('LEADER_CN_XIAOYAN_CIVICS',				'CIVIC_NATURAL_HISTORY',				1		), 
		-- DISTRICTS
		('LEADER_CN_XIAOYAN_DISTRICTS',				'DISTRICT_ENCAMPMENT',					1		),
		('LEADER_CN_XIAOYAN_DISTRICTS',				'DISTRICT_COMMERCIAL_HUB',				1		),
		('LEADER_CN_XIAOYAN_DISTRICTS',				'DISTRICT_THEATER',						1		),
		-- BUILDINGS
		('LEADER_CN_XIAOYAN_BUILDINGS',				'BUILDING_MONUMENT',					1		), 
		('LEADER_CN_XIAOYAN_BUILDINGS',				'BUILDING_LIBRARY',						1		),
		('LEADER_CN_XIAOYAN_BUILDINGS',				'BUILDING_MARKET',						1		),
		('LEADER_CN_XIAOYAN_BUILDINGS',				'BUILDING_STABLE',						1		),
		('LEADER_CN_XIAOYAN_BUILDINGS',				'BUILDING_AMPHITHEATER',				1		),
		('LEADER_CN_XIAOYAN_BUILDINGS',				'BUILDING_STOCK_EXCHANGE',				1		),
		-- WONDERS
		('LEADER_CN_XIAOYAN_BUILDINGS',				'BUILDING_BIG_BEN',						1		),
		('LEADER_CN_XIAOYAN_BUILDINGS',				'BUILDING_COLOSSUS',					1		),
		('LEADER_CN_XIAOYAN_BUILDINGS',				'BUILDING_EIFFEL_TOWER',				1		),
		('LEADER_CN_XIAOYAN_BUILDINGS',				'BUILDING_FORBIDDEN_CITY',				1		),
		('LEADER_CN_XIAOYAN_BUILDINGS',				'BUILDING_GREAT_ZIMBABWE',				1		),
		('LEADER_CN_XIAOYAN_BUILDINGS',				'BUILDING_OXFORD_UNIVERSITY',			1		),
		('LEADER_CN_XIAOYAN_BUILDINGS',				'BUILDING_PYRAMIDS',					1		),
		-- DIPLOMACY
		('LEADER_CN_XIAOYAN_DIPLOMACY',				'DIPLOACTION_PROPOSE_TRADE',			1		),
		('LEADER_CN_XIAOYAN_DIPLOMACY',				'DIPLOACTION_RESIDENT_EMBASSY',			1		),
		('LEADER_CN_XIAOYAN_DIPLOMACY',				'DIPLOACTION_DIPLOMATIC_DELEGATION',	1		),
		('LEADER_CN_XIAOYAN_DIPLOMACY',				'DIPLOACTION_DECLARE_FRIENDSHIP',		1		),
		('LEADER_CN_XIAOYAN_DIPLOMACY',				'DIPLOACTION_ALLIANCE',					1		),
		('LEADER_CN_XIAOYAN_DIPLOMACY',				'DIPLOACTION_ALLIANCE_RESEARCH',		1		), -- XP1
		('LEADER_CN_XIAOYAN_DIPLOMACY',				'DIPLOACTION_ALLIANCE_MILITARY',		1		), -- XP1
		('LEADER_CN_XIAOYAN_DIPLOMACY',				'DIPLOACTION_ALLIANCE_ECONOMIC',		1		), -- XP1
		('LEADER_CN_XIAOYAN_DIPLOMACY',				'DIPLOACTION_ALLIANCE_CULTURAL',		1		), -- XP1
		('LEADER_CN_XIAOYAN_DIPLOMACY',				'DIPLOACTION_ALLIANCE_RELIGIOUS',		1		), -- XP1
		-- ALLIANCES (XP1)
		('LEADER_CN_XIAOYAN_ALLIANCES',				'ALLIANCE_RESEARCH',					1		),
		('LEADER_CN_XIAOYAN_ALLIANCES',				'ALLIANCE_CULTURAL',					1		),
		('LEADER_CN_XIAOYAN_ALLIANCES',				'ALLIANCE_MILITARY',					1		),
		('LEADER_CN_XIAOYAN_ALLIANCES',				'ALLIANCE_ECONOMIC',					1		),
		('LEADER_CN_XIAOYAN_ALLIANCES',				'ALLIANCE_RELIGIOUS',					1		),
		-- COMMEMORATIONS (XP1)
		('LEADER_CN_XIAOYAN_COMMEMORATIONS',		'COMMEMORATION_CULTURAL',				1		),
		-- DISCUSSIONS (XP2)
		('LEADER_CN_XIAOYAN_DISCUSSIONS',			'WC_RES_LUXURY',						1		),
		('LEADER_CN_XIAOYAN_DISCUSSIONS',			'WC_EMERGENCY_BACKSTAB',				1		),
		('LEADER_CN_XIAOYAN_DISCUSSIONS',			'WC_RES_TRADE_TREATY',					1		);

INSERT INTO AiFavoredItems
		(ListType,							    Item,						        Favored,	Value,	StringVal					)
VALUES  -- EXPANSION
		('LEADER_CN_XIAOYAN_EXPANSION',			'Resource Class',			        1,			5,		'RESOURCECLASS_BONUS'		),
		('LEADER_CN_XIAOYAN_EXPANSION',			'Resource Class',			        1,			10,		'RESOURCECLASS_STRATEGIC'	),
		('LEADER_CN_XIAOYAN_EXPANSION',			'Resource Class',			        1,			10,		'RESOURCECLASS_LUXURY'		),
		('LEADER_CN_XIAOYAN_EXPANSION',			'New Resources',			        1,			20,		NULL						),
		-- PSUEDOS
		('LEADER_CN_XIAOYAN_PSUEDOS',			'PSEUDOYIELD_UNIT_RELIGIOUS',	    1,			50,		NULL						),
		('LEADER_CN_XIAOYAN_PSUEDOS',			'PSEUDOYIELD_GPP_PROPHET',	        1,			15,		NULL						),
        ('LEADER_CN_XIAOYAN_PSUEDOS',			'PSEUDOYIELD_GPP_WRITER',	        1,			5,		NULL						),
        ('LEADER_CN_XIAOYAN_PSUEDOS',			'PSEUDOYIELD_GPP_MUSICIAN',	        1,			5,		NULL						),
        ('LEADER_CN_XIAOYAN_PSUEDOS',			'PSEUDOYIELD_GPP_ARTIST',	        1,			5,		NULL						),
		('LEADER_CN_XIAOYAN_PSUEDOS',			'PSEUDOYIELD_GREATWORK_RELIGIOUS',	1,			15,		NULL						);